version: "3.2"

services:
  nc_postgresql:
    image: postgres:13
    container_name: nc_postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=nc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - nc-db:/var/lib/postgresql/data
    networks:
      nc_network:
        ipv4_address: 10.3.0.5

  nc_redis:
    image: "redis:alpine"
    container_name: nc_redis
    networks:
      nc_network:
        ipv4_address: 10.3.0.8

  nc_celery_worker:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: nc_celery
    command: bash -c "dockerize -wait tcp://nc_postgresql:5432 -timeout 1m && dockerize -wait tcp://nc_redis:6379 -timeout 1m && celery -A nc worker --loglevel=info"
    volumes:
      - type: bind
        source: ./backend
        target: /home/app/web
    environment:
      - POSTGRES_HOST=10.3.0.5
      - POSTGRES_DB=nc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - DEBUG=True
      - AWS_ACCESS_KEY_ID=<PLEASE_INPUT>
      - AWS_SECRET_ACCESS_KEY=<PLEASE_INPUT>
      - AWS_STORAGE_BUCKET_NAME=<PLEASE_INPUT>
      - AWS_S3_REGION_NAME=<PLEASE_INPUT>
      - SECRET_KEY=django-insecure
      - CELERY_BROKER_URL=redis://nc_redis:6379/0
    depends_on:
      - nc_postgresql
      - nc_redis
    networks:
      nc_network:
        ipv4_address: 10.3.0.9

  nc_backend:
    expose:
      - 8000
    ports:
      - 8000:8000
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: nc_backend
    command: gunicorn nc.wsgi:application --workers 2 --thread 3 --bind 0.0.0.0:8000 --reload
    volumes:
      - type: bind
        source: ./backend
        target: /home/app/web
    environment:
      - EXTERNAL_IP=127.0.0.1
      - POSTGRES_HOST=10.3.0.5
      - POSTGRES_DB=nc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - DEBUG=True
      - AWS_ACCESS_KEY_ID=<PLEASE_INPUT>
      - AWS_SECRET_ACCESS_KEY=<PLEASE_INPUT>
      - AWS_STORAGE_BUCKET_NAME=<PLEASE_INPUT>
      - AWS_S3_REGION_NAME=<PLEASE_INPUT>
      - SECRET_KEY=django-insecure
      - CELERY_BROKER_URL=redis://nc_redis:6379/0
    restart: always
    depends_on:
      - nc_postgresql
    networks:
      nc_network:
        ipv4_address: 10.3.0.7

  nc_frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: nc_frontend
    entrypoint: bash -c "yarn && yarn start"
    volumes:
      - ./frontend/src:/app/src
      - type: bind
        source: ./frontend/package.json
        target: /app/package.json
    environment:
      - REACT_APP_API_BASE_URL=http://10.3.0.7:8000/api/v1
      - REACT_APP_TIME_OUT=25000
    ports:
      - 3000:3000
    depends_on:
      - nc_backend
    restart: always
    networks:
      nc_network:
        ipv4_address: 10.3.0.6

networks:
  nc_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.0.0/16

volumes:
  nc-db:
    driver: local
